#!/usr/bin/env bash
set -euo pipefail

# Open JTalk wrapper for Speech Dispatcher GenericExecuteSynth
# Reads text from stdin, generates a wav file, and plays it.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="${LOG_DIR:-"${SCRIPT_DIR}/../logs"}"

mkdir -p "${LOG_DIR}"

TMP_DIR="$(mktemp -d)"
cleanup() {
  if [[ "${OPENJTALK_DEBUG:-0}" == "1" ]]; then
    echo "DEBUG: temp dir preserved at ${TMP_DIR}" >&2
  else
    rm -rf "${TMP_DIR}"
  fi
}
trap cleanup EXIT

TEXT_FILE="${TMP_DIR}/input.txt"
TEXT_NORM_FILE="${TMP_DIR}/input_norm.txt"
WAV_FILE="${TMP_DIR}/output.wav"
LOG_TEXT_PATH="${OPENJTALK_LOG_TEXT_PATH:-"${LOG_DIR}/openjtalk_text.log"}"

cat > "${TEXT_FILE}"

if [[ ! -s "${TEXT_FILE}" ]]; then
  echo "No input text" >&2
  exit 1
fi

# Apply word replacements (optional)
REPLACE_FILE="${OPENJTALK_REPLACE_FILE:-"${SCRIPT_DIR}/../conf/word_replacements.tsv"}"
if [[ -f "${REPLACE_FILE}" ]]; then
  OPENJTALK_TEXT_FILE="${TEXT_FILE}" OPENJTALK_TEXT_NORM_FILE="${TEXT_NORM_FILE}" OPENJTALK_REPLACE_FILE="${REPLACE_FILE}" python3 - <<'PY'
import os, sys
src = os.environ.get("OPENJTALK_TEXT_FILE")
dst = os.environ.get("OPENJTALK_TEXT_NORM_FILE")
rep = os.environ.get("OPENJTALK_REPLACE_FILE")

with open(src, "r", encoding="utf-8") as f:
    text = f.read()

replacements = []
with open(rep, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "\t" not in line:
            continue
        a, b = line.split("\t", 1)
        replacements.append((a, b))

for a, b in replacements:
    text = text.replace(a, b)

with open(dst, "w", encoding="utf-8") as f:
    f.write(text)
PY
else
  cp "${TEXT_FILE}" "${TEXT_NORM_FILE}"
fi

if [[ "${OPENJTALK_LOG_TEXT:-0}" == "1" ]]; then
  {
    printf '[%s]\n' "$(date '+%Y-%m-%d %H:%M:%S')"
    cat "${TEXT_NORM_FILE}"
    printf '\n----\n'
  } >> "${LOG_TEXT_PATH}"
fi

# Resolve Open JTalk dictionary path
DICT_CANDIDATES=(
  "${OPENJTALK_DICT:-}"
  "/var/lib/mecab/dic/open-jtalk/naist-jdic"
  "/usr/share/mecab/dic/open-jtalk/naist-jdic"
)
DICT_PATH=""
for d in "${DICT_CANDIDATES[@]}"; do
  if [[ -n "${d}" && -d "${d}" ]]; then
    DICT_PATH="${d}"
    break
  fi
done

if [[ -z "${DICT_PATH}" ]]; then
  echo "Open JTalk dictionary not found. Set OPENJTALK_DICT." >&2
  exit 1
fi

# Resolve HTS voice path
VOICE_CANDIDATES=(
  "${OPENJTALK_VOICE:-}"
  "/usr/share/hts-voice/nitech-jp-atr503-m001/nitech_jp_atr503_m001.htsvoice"
  "/usr/share/hts-voice/mei/mei_normal.htsvoice"
)
VOICE_PATH=""
for v in "${VOICE_CANDIDATES[@]}"; do
  if [[ -n "${v}" && -f "${v}" ]]; then
    VOICE_PATH="${v}"
    break
  fi
done

if [[ -z "${VOICE_PATH}" ]]; then
  echo "HTS voice not found. Set OPENJTALK_VOICE." >&2
  exit 1
fi

# Resolve Open JTalk user dictionary (optional)
USER_DICT_CANDIDATES=(
  "${OPENJTALK_USER_DICT:-}"
  "${SCRIPT_DIR}/../conf/openjtalk_userdict.dic"
)
USER_DICT_PATH=""
for u in "${USER_DICT_CANDIDATES[@]}"; do
  if [[ -n "${u}" && -f "${u}" ]]; then
    USER_DICT_PATH="${u}"
    break
  fi
done

# Build a temporary mecabrc so Open JTalk can use the user dictionary
MECABRC_PATH="${TMP_DIR}/mecabrc"
{
  echo "; Auto-generated by openjtalk_say.sh"
  echo "dicdir = ${DICT_PATH}"
  if [[ -n "${USER_DICT_PATH}" ]]; then
    echo "userdic = ${USER_DICT_PATH}"
  fi
} > "${MECABRC_PATH}"

if [[ "${OPENJTALK_DEBUG:-0}" == "1" ]]; then
  echo "DEBUG: OPENJTALK_DICT=${DICT_PATH}" >&2
  echo "DEBUG: OPENJTALK_VOICE=${VOICE_PATH}" >&2
  echo "DEBUG: OPENJTALK_USER_DICT=${USER_DICT_PATH}" >&2
  echo "DEBUG: OPENJTALK_REPLACE_FILE=${REPLACE_FILE}" >&2
  echo "DEBUG: TEXT_FILE=${TEXT_FILE}" >&2
  echo "DEBUG: TEXT_NORM_FILE=${TEXT_NORM_FILE}" >&2
  echo "DEBUG: MECABRC_PATH=${MECABRC_PATH}" >&2
  echo "DEBUG: mecabrc contents:" >&2
  sed -n '1,200p' "${MECABRC_PATH}" >&2
fi

# Optional voice parameters
SPEED="${OPENJTALK_SPEED:-1.0}"
ALPHA="${OPENJTALK_ALPHA:-0.55}"
BETA="${OPENJTALK_BETA:-0.0}"

MECABRC="${MECABRC_PATH}" open_jtalk \
  -x "${DICT_PATH}" \
  -m "${VOICE_PATH}" \
  -r "${SPEED}" \
  -a "${ALPHA}" \
  -b "${BETA}" \
  -ow "${WAV_FILE}" \
  "${TEXT_NORM_FILE}"

if [[ ! -s "${WAV_FILE}" ]]; then
  echo "Failed to generate wav" >&2
  exit 1
fi

if [[ "${OPENJTALK_NO_PLAY:-0}" == "1" ]]; then
  echo "WAV: ${WAV_FILE}"
  exit 0
fi

if command -v aplay >/dev/null 2>&1; then
  aplay -q "${WAV_FILE}"
elif command -v pw-play >/dev/null 2>&1; then
  pw-play "${WAV_FILE}"
elif command -v paplay >/dev/null 2>&1; then
  paplay "${WAV_FILE}"
else
  echo "No audio player found (aplay, pw-play, paplay)." >&2
  exit 1
fi
